CREATE TABLE DBUSER ( 
  USER_ID       INT NOT NULL, 
  USERNAME      VARCHAR (20)  NOT NULL, 
  CREATED_BY    VARCHAR (20)  NOT NULL, 
  CREATED_DATE  DATE          NOT NULL, 
  CONSTRAINT DispClass_primary PRIMARY KEY ( USER_ID ) 
)